// <auto-generated />
using System;
using Kennel.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Kennel.Infrastructure.Migrations
{
    [DbContext(typeof(KennelDbContext))]
    [Migration("20210422131825_Kennel")]
    partial class Kennel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Kennel.Domain.Animal.Animal", b =>
                {
                    b.Property<Guid>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProtokolId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AnimalId");

                    b.HasIndex("ProtokolId");

                    b.ToTable("Animals");
                });

            modelBuilder.Entity("Kennel.Domain.Kennel.Kennel", b =>
                {
                    b.Property<Guid>("KennelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("KennelId");

                    b.HasIndex("OwnerId")
                        .IsUnique();

                    b.ToTable("Kennels");
                });

            modelBuilder.Entity("Kennel.Domain.Litter.Litter", b =>
                {
                    b.Property<Guid>("AnimalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LitterId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AnimalId");

                    b.ToTable("Litters");
                });

            modelBuilder.Entity("Kennel.Domain.Owner.Owner", b =>
                {
                    b.Property<Guid>("OwnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OwnerId");

                    b.ToTable("Owners");
                });

            modelBuilder.Entity("Kennel.Domain.Protokol.Protokol", b =>
                {
                    b.Property<Guid>("ProtokolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("KennelId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ProtokolId");

                    b.HasIndex("KennelId")
                        .IsUnique();

                    b.ToTable("Protokols");
                });

            modelBuilder.Entity("Kennel.Domain.Animal.Animal", b =>
                {
                    b.HasOne("Kennel.Domain.Protokol.Protokol", "Protokol")
                        .WithMany("Animals")
                        .HasForeignKey("ProtokolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Kennel.Domain.Animal.AnimalId", "Id", b1 =>
                        {
                            b1.Property<Guid>("AnimalId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("AnimalId");

                            b1.ToTable("Animals");

                            b1.WithOwner()
                                .HasForeignKey("AnimalId");
                        });

                    b.OwnsOne("Kennel.Domain.Animal.BirthDate", "BirthDate", b1 =>
                        {
                            b1.Property<Guid>("AnimalId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("Value")
                                .HasColumnType("datetime2");

                            b1.HasKey("AnimalId");

                            b1.ToTable("Animals");

                            b1.WithOwner()
                                .HasForeignKey("AnimalId");
                        });

                    b.OwnsOne("Kennel.Domain.Animal.Color", "Color", b1 =>
                        {
                            b1.Property<Guid>("AnimalId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("AnimalId");

                            b1.ToTable("Animals");

                            b1.WithOwner()
                                .HasForeignKey("AnimalId");
                        });

                    b.OwnsOne("Kennel.Domain.Animal.DeathDate", "DeathDate", b1 =>
                        {
                            b1.Property<Guid>("AnimalId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("Value")
                                .HasColumnType("datetime2");

                            b1.HasKey("AnimalId");

                            b1.ToTable("Animals");

                            b1.WithOwner()
                                .HasForeignKey("AnimalId");
                        });

                    b.OwnsOne("Kennel.Domain.Animal.Gender", "Gender", b1 =>
                        {
                            b1.Property<Guid>("AnimalId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("Value")
                                .HasColumnType("bit");

                            b1.HasKey("AnimalId");

                            b1.ToTable("Animals");

                            b1.WithOwner()
                                .HasForeignKey("AnimalId");
                        });

                    b.OwnsOne("Kennel.Domain.Animal.IsBreedable", "IsBreedable", b1 =>
                        {
                            b1.Property<Guid>("AnimalId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("Value")
                                .HasColumnType("bit");

                            b1.HasKey("AnimalId");

                            b1.ToTable("Animals");

                            b1.WithOwner()
                                .HasForeignKey("AnimalId");
                        });

                    b.OwnsOne("Kennel.Domain.Animal.IsDeleted", "IsDeleted", b1 =>
                        {
                            b1.Property<Guid>("AnimalId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("Value")
                                .HasColumnType("bit");

                            b1.HasKey("AnimalId");

                            b1.ToTable("Animals");

                            b1.WithOwner()
                                .HasForeignKey("AnimalId");
                        });

                    b.OwnsOne("Kennel.Domain.Animal.PedigreeName", "PedigreeName", b1 =>
                        {
                            b1.Property<Guid>("AnimalId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("AnimalId");

                            b1.ToTable("Animals");

                            b1.WithOwner()
                                .HasForeignKey("AnimalId");
                        });

                    b.OwnsOne("Kennel.Domain.Animal.RegNo", "RegNo", b1 =>
                        {
                            b1.Property<Guid>("AnimalId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Value")
                                .HasColumnType("int");

                            b1.HasKey("AnimalId");

                            b1.ToTable("Animals");

                            b1.WithOwner()
                                .HasForeignKey("AnimalId");
                        });

                    b.OwnsOne("Kennel.Domain.Animal.SubRaceId", "SubRaceId", b1 =>
                        {
                            b1.Property<Guid>("AnimalId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("AnimalId");

                            b1.ToTable("Animals");

                            b1.WithOwner()
                                .HasForeignKey("AnimalId");
                        });

                    b.Navigation("BirthDate");

                    b.Navigation("Color");

                    b.Navigation("DeathDate");

                    b.Navigation("Gender");

                    b.Navigation("Id");

                    b.Navigation("IsBreedable");

                    b.Navigation("IsDeleted");

                    b.Navigation("PedigreeName");

                    b.Navigation("Protokol");

                    b.Navigation("RegNo");

                    b.Navigation("SubRaceId");
                });

            modelBuilder.Entity("Kennel.Domain.Kennel.Kennel", b =>
                {
                    b.HasOne("Kennel.Domain.Owner.Owner", "Owner")
                        .WithOne("Kennel")
                        .HasForeignKey("Kennel.Domain.Kennel.Kennel", "OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Kennel.Domain.Kennel.IsDeleted", "IsDeleted", b1 =>
                        {
                            b1.Property<Guid>("KennelId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("Value")
                                .HasColumnType("bit");

                            b1.HasKey("KennelId");

                            b1.ToTable("Kennels");

                            b1.WithOwner()
                                .HasForeignKey("KennelId");
                        });

                    b.OwnsOne("Kennel.Domain.Kennel.KennelId", "Id", b1 =>
                        {
                            b1.Property<Guid>("KennelId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("KennelId");

                            b1.ToTable("Kennels");

                            b1.WithOwner()
                                .HasForeignKey("KennelId");
                        });

                    b.OwnsOne("Kennel.Domain.Kennel.KennelName", "KennelName", b1 =>
                        {
                            b1.Property<Guid>("KennelId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("KennelId");

                            b1.ToTable("Kennels");

                            b1.WithOwner()
                                .HasForeignKey("KennelId");
                        });

                    b.OwnsOne("Kennel.Domain.Kennel.KennelSmiley", "KennelSmiley", b1 =>
                        {
                            b1.Property<Guid>("KennelId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("KennelId");

                            b1.ToTable("Kennels");

                            b1.WithOwner()
                                .HasForeignKey("KennelId");
                        });

                    b.Navigation("Id");

                    b.Navigation("IsDeleted");

                    b.Navigation("KennelName");

                    b.Navigation("KennelSmiley");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Kennel.Domain.Litter.Litter", b =>
                {
                    b.HasOne("Kennel.Domain.Animal.Animal", "Animal")
                        .WithMany("Litters")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Kennel.Domain.Litter.ChildAmount", "ChildAmount", b1 =>
                        {
                            b1.Property<Guid>("LitterAnimalId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Value")
                                .HasColumnType("int");

                            b1.HasKey("LitterAnimalId");

                            b1.ToTable("Litters");

                            b1.WithOwner()
                                .HasForeignKey("LitterAnimalId");
                        });

                    b.OwnsOne("Kennel.Domain.Litter.IsDeleted", "IsDeleted", b1 =>
                        {
                            b1.Property<Guid>("LitterAnimalId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("Value")
                                .HasColumnType("bit");

                            b1.HasKey("LitterAnimalId");

                            b1.ToTable("Litters");

                            b1.WithOwner()
                                .HasForeignKey("LitterAnimalId");
                        });

                    b.OwnsOne("Kennel.Domain.Litter.LitterBirthDate", "LitterBirthDate", b1 =>
                        {
                            b1.Property<Guid>("LitterAnimalId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("Value")
                                .HasColumnType("datetime2");

                            b1.HasKey("LitterAnimalId");

                            b1.ToTable("Litters");

                            b1.WithOwner()
                                .HasForeignKey("LitterAnimalId");
                        });

                    b.OwnsOne("Kennel.Domain.Litter.LitterId", "Id", b1 =>
                        {
                            b1.Property<Guid>("LitterAnimalId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("LitterAnimalId");

                            b1.ToTable("Litters");

                            b1.WithOwner()
                                .HasForeignKey("LitterAnimalId");
                        });

                    b.OwnsOne("Kennel.Domain.Litter.LitterName", "LitterName", b1 =>
                        {
                            b1.Property<Guid>("LitterAnimalId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("LitterAnimalId");

                            b1.ToTable("Litters");

                            b1.WithOwner()
                                .HasForeignKey("LitterAnimalId");
                        });

                    b.Navigation("Animal");

                    b.Navigation("ChildAmount");

                    b.Navigation("Id");

                    b.Navigation("IsDeleted");

                    b.Navigation("LitterBirthDate");

                    b.Navigation("LitterName");
                });

            modelBuilder.Entity("Kennel.Domain.Owner.Owner", b =>
                {
                    b.OwnsOne("Kennel.Domain.Owner.City", "City", b1 =>
                        {
                            b1.Property<Guid>("OwnerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("OwnerId");

                            b1.ToTable("Owners");

                            b1.WithOwner()
                                .HasForeignKey("OwnerId");
                        });

                    b.OwnsOne("Kennel.Domain.Owner.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("OwnerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("OwnerId");

                            b1.ToTable("Owners");

                            b1.WithOwner()
                                .HasForeignKey("OwnerId");
                        });

                    b.OwnsOne("Kennel.Domain.Owner.FirstName", "FirstName", b1 =>
                        {
                            b1.Property<Guid>("OwnerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("OwnerId");

                            b1.ToTable("Owners");

                            b1.WithOwner()
                                .HasForeignKey("OwnerId");
                        });

                    b.OwnsOne("Kennel.Domain.Owner.IsDeleted", "IsDeleted", b1 =>
                        {
                            b1.Property<Guid>("OwnerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("Value")
                                .HasColumnType("bit");

                            b1.HasKey("OwnerId");

                            b1.ToTable("Owners");

                            b1.WithOwner()
                                .HasForeignKey("OwnerId");
                        });

                    b.OwnsOne("Kennel.Domain.Owner.LastName", "LastName", b1 =>
                        {
                            b1.Property<Guid>("OwnerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("OwnerId");

                            b1.ToTable("Owners");

                            b1.WithOwner()
                                .HasForeignKey("OwnerId");
                        });

                    b.OwnsOne("Kennel.Domain.Owner.OwnerId", "Id", b1 =>
                        {
                            b1.Property<Guid>("OwnerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("OwnerId");

                            b1.ToTable("Owners");

                            b1.WithOwner()
                                .HasForeignKey("OwnerId");
                        });

                    b.OwnsOne("Kennel.Domain.Owner.PhoneNo", "PhoneNo", b1 =>
                        {
                            b1.Property<Guid>("OwnerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("OwnerId");

                            b1.ToTable("Owners");

                            b1.WithOwner()
                                .HasForeignKey("OwnerId");
                        });

                    b.OwnsOne("Kennel.Domain.Owner.Street", "Street", b1 =>
                        {
                            b1.Property<Guid>("OwnerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("OwnerId");

                            b1.ToTable("Owners");

                            b1.WithOwner()
                                .HasForeignKey("OwnerId");
                        });

                    b.OwnsOne("Kennel.Domain.Owner.Zipcode", "Zipcode", b1 =>
                        {
                            b1.Property<Guid>("OwnerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("OwnerId");

                            b1.ToTable("Owners");

                            b1.WithOwner()
                                .HasForeignKey("OwnerId");
                        });

                    b.Navigation("City");

                    b.Navigation("Email");

                    b.Navigation("FirstName");

                    b.Navigation("Id");

                    b.Navigation("IsDeleted");

                    b.Navigation("LastName");

                    b.Navigation("PhoneNo");

                    b.Navigation("Street");

                    b.Navigation("Zipcode");
                });

            modelBuilder.Entity("Kennel.Domain.Protokol.Protokol", b =>
                {
                    b.HasOne("Kennel.Domain.Kennel.Kennel", "Kennel")
                        .WithOne("Protokol")
                        .HasForeignKey("Kennel.Domain.Protokol.Protokol", "KennelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Kennel.Domain.Protokol.IsDeleted", "IsDeleted", b1 =>
                        {
                            b1.Property<Guid>("ProtokolId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("Value")
                                .HasColumnType("bit");

                            b1.HasKey("ProtokolId");

                            b1.ToTable("Protokols");

                            b1.WithOwner()
                                .HasForeignKey("ProtokolId");
                        });

                    b.OwnsOne("Kennel.Domain.Protokol.ProtokolId", "Id", b1 =>
                        {
                            b1.Property<Guid>("ProtokolId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("ProtokolId");

                            b1.ToTable("Protokols");

                            b1.WithOwner()
                                .HasForeignKey("ProtokolId");
                        });

                    b.Navigation("Id");

                    b.Navigation("IsDeleted");

                    b.Navigation("Kennel");
                });

            modelBuilder.Entity("Kennel.Domain.Animal.Animal", b =>
                {
                    b.Navigation("Litters");
                });

            modelBuilder.Entity("Kennel.Domain.Kennel.Kennel", b =>
                {
                    b.Navigation("Protokol");
                });

            modelBuilder.Entity("Kennel.Domain.Owner.Owner", b =>
                {
                    b.Navigation("Kennel");
                });

            modelBuilder.Entity("Kennel.Domain.Protokol.Protokol", b =>
                {
                    b.Navigation("Animals");
                });
#pragma warning restore 612, 618
        }
    }
}
